---
- hosts: all
  vars_files:
    - variables.yml
  become: yes
  become_user: "{{ server_user }}"
  roles:
    - prereqs
    - fabric-dev-server
    - composer-cards
    - composer-playground
    - reboot
