---
- name: Docker needs to start on reboot
  become_user: root
  lineinfile: dest=/etc/rc.local line='service docker start' insertafter='EOF' state=present

- name: Fabric needs to start on reboot
  become_user: root
  lineinfile: dest=/etc/rc.local line='/home/{{ server_user }}/fabric-tools/startFabric.sh' insertafter='EOF' state=present

- name: Make rc.local executable
  become_user: root
  file:
    path: /etc/rc.local
    mode: 0755

- name: composer-playground needs to start on reboot
  become_user: root
  become: yes
  lineinfile: dest=/etc/rc.local line='docker run -d --name {{ playground_container_name }} -p 8080:8080 -v ~/.composer:/home/composer/.composer {{ playground_image_tag }}' insertafter='EOF' state=present

- name: Start fabric containers
  shell: >
    cd ~/fabric-tools && ./startFabric.sh
  args:
    executable: /bin/bash
