---
- name: Creates directory
  file: path=~/fabric-tools state=directory

- name: Adding the path in the bashrc files
  lineinfile: dest=~/.bashrc line='export FABRIC_VERSION={{ hyperledger_fabric_version }}' insertafter='EOF' state=present

- name: Configure globally which FABRIC_VERSION to use
  shell: >
    . ~/.bashrc && echo $FABRIC_VERSION

- name: Download fabric-dev-servers.zip
  get_url:
    url: "{{ fabric_dev_servers_zip_url }}"
    dest: ~/fabric-tools/fabric-dev-servers.zip
    mode: 0755

- name: Extract fabric-dev-servers.zip into ~/fabric-tools
  unarchive:
    src: ~/fabric-tools/fabric-dev-servers.zip
    dest: ~/fabric-tools
    remote_src: yes

- name: Download fabric docker images by script
  shell: >
    cd ~/fabric-tools && ./downloadFabric.sh && touch ~/downloaded-images
    creates=~/downloaded-images
  args:
    executable: /bin/bash
