---
- name: Install packages to allow apt to use a repository over HTTPS
  become_user: root
  package: pkg={{item}} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

- name: Add GPG key for Docker
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add the Docker repository to the apt sources list
  become_user: root
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install Docker
  become_user: root
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify:
    - start docker

- name: Install Docker Compose
  become_user: root
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    force: true
    owner: "{{ server_user }}"
    group: docker
    mode: 0755

- name: Add the default user to the docker group
  become_user: root
  user:
    name: "{{ server_user }}"
    group: docker
    append: yes
